### ISSUE TITLE
usage with non-sdk based csproj files

### ISSUE THREAD

**Issue by chinwobble** [AArnott/CodeGeneration.Roslyn#167]
I want to use code generation in a UWP app. 
Unfortunately UWP doesn't look like it is supported by SDK based projects yet.

Is there any workaround to use code generation with them?

**Comment by amis92** [comment]
Nothing I know about, unfortunately.

**Comment by AArnott** [comment]
Supporting non-SDK style projects hasn't been a priority for us, and isn't likely to be going forward either. UWP will likely support SDK style projects eventually, since that's the way things are going.
In the meantime, I would suggest you try to do your CG.R work in another SDK-style project and reference that project from your UWP project.
